import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1778273424632 implements MigrationInterface {
    name = 'InitialSchema1778273424632'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "locations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" text NOT NULL, "address" text NOT NULL, "phone" text, "timezone" text NOT NULL DEFAULT 'America/New_York', "active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_7cc1c9e3853b94816c094825e74" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "location_hours" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "location_id" uuid NOT NULL, "day_of_week" integer NOT NULL, "open_time" TIME NOT NULL, "close_time" TIME NOT NULL, "is_closed" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_27d66935e143a67304270519629" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_39d361bcd1c543a8c00011fe0c" ON "location_hours" ("location_id", "day_of_week") `);
        await queryRunner.query(`CREATE TABLE "location_settings" ("location_id" uuid NOT NULL, "mobile_ordering_paused" boolean NOT NULL DEFAULT false, "current_wait_minutes" integer NOT NULL DEFAULT '5', "scheduled_ordering" boolean NOT NULL DEFAULT true, "max_schedule_days" integer NOT NULL DEFAULT '7', "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_84d2853faad00c6eebb7cd6e8c0" PRIMARY KEY ("location_id"))`);
        await queryRunner.query(`CREATE TABLE "customers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" text NOT NULL, "phone" text, "full_name" text NOT NULL, "cognito_id" text, "password_hash" text, "loyalty_points" integer NOT NULL DEFAULT '0', "loyalty_tier" text NOT NULL DEFAULT 'BRONZE', "stripe_customer_id" text, "push_token" text, "last_visit_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_8536b8b85c06969f84f0c098b03" UNIQUE ("email"), CONSTRAINT "PK_133ec679a801fab5e070f73d3ea" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_8536b8b85c06969f84f0c098b0" ON "customers" ("email") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_239f870c0c4c1d6b68eb016dfb" ON "customers" ("cognito_id") WHERE cognito_id IS NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."staff_role_enum" AS ENUM('OWNER', 'MANAGER', 'BARISTA')`);
        await queryRunner.query(`CREATE TABLE "staff_users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "location_id" uuid NOT NULL, "email" text NOT NULL, "full_name" text NOT NULL, "role" "public"."staff_role_enum" NOT NULL, "password_hash" text NOT NULL, "cognito_id" text, "active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_4f32dd66546226ea64f5573b770" UNIQUE ("email"), CONSTRAINT "PK_c6b167335377df69f7910c2c75e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_4f32dd66546226ea64f5573b77" ON "staff_users" ("email") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_5cdfddaf549b53bbc3d723dc2c" ON "staff_users" ("cognito_id") WHERE cognito_id IS NOT NULL`);
        await queryRunner.query(`CREATE TABLE "menu_categories" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "location_id" uuid NOT NULL, "name" text NOT NULL, "sort_order" integer NOT NULL DEFAULT '0', "active" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_124ae987900336f983881cb04e6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "menu_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "category_id" uuid NOT NULL, "clover_item_id" text, "name" text NOT NULL, "description" text, "base_price_cents" integer NOT NULL, "image_url" text, "active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_57e6188f929e5dc6919168620c8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c9f448f6e4d50fc4e1d4a783ca" ON "menu_items" ("clover_item_id") `);
        await queryRunner.query(`CREATE TABLE "modifier_groups" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "item_id" uuid NOT NULL, "name" text NOT NULL, "required" boolean NOT NULL DEFAULT false, "multi_select" boolean NOT NULL DEFAULT false, "sort_order" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_b3cea1c985339de5ea73d77101d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "modifiers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "group_id" uuid NOT NULL, "clover_mod_id" text, "name" text NOT NULL, "price_cents" integer NOT NULL DEFAULT '0', "sort_order" integer NOT NULL DEFAULT '0', "active" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_f4d68e3a0c8a835c06a9fa27f7e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_68f9a6a26b1cb62380a64b0be3" ON "modifiers" ("clover_mod_id") `);
        await queryRunner.query(`CREATE TABLE "inventory" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "item_id" uuid NOT NULL, "location_id" uuid NOT NULL, "available" boolean NOT NULL DEFAULT true, "quantity_left" integer, "sold_out_at" TIMESTAMP WITH TIME ZONE, "updated_by" uuid, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_a4a62e5d0870b0e0476bc5e3bbc" UNIQUE ("item_id", "location_id"), CONSTRAINT "PK_82aa5da437c5bbfb80703b08309" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "pricing_rules" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "location_id" uuid NOT NULL, "tax_rate_bps" integer NOT NULL, "tip_options" integer array NOT NULL DEFAULT '{15,18,20,25}'::int[], "active" boolean NOT NULL DEFAULT true, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_fda27bb8db4630894decda61ff6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."order_status_enum" AS ENUM('DRAFT', 'PENDING_PAYMENT', 'PAID', 'ACCEPTED', 'IN_PROGRESS', 'READY', 'PICKED_UP', 'CANCELLED', 'REFUNDED', 'FAILED')`);
        await queryRunner.query(`CREATE TYPE "public"."payment_status_enum" AS ENUM('REQUIRES_PAYMENT', 'PROCESSING', 'SUCCEEDED', 'FAILED', 'REFUNDED', 'PARTIALLY_REFUNDED')`);
        await queryRunner.query(`CREATE TYPE "public"."clover_sync_status_enum" AS ENUM('NOT_SENT', 'PENDING', 'SENT', 'FAILED', 'MANUAL_REQUIRED')`);
        await queryRunner.query(`CREATE TYPE "public"."pickup_type_enum" AS ENUM('ASAP', 'SCHEDULED')`);
        await queryRunner.query(`CREATE TABLE "orders" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "customer_id" uuid NOT NULL, "location_id" uuid NOT NULL, "idempotency_key" text NOT NULL, "order_status" "public"."order_status_enum" NOT NULL DEFAULT 'DRAFT', "payment_status" "public"."payment_status_enum" NOT NULL DEFAULT 'REQUIRES_PAYMENT', "clover_sync_status" "public"."clover_sync_status_enum" NOT NULL DEFAULT 'NOT_SENT', "pickup_type" "public"."pickup_type_enum" NOT NULL DEFAULT 'ASAP', "scheduled_pickup_at" TIMESTAMP WITH TIME ZONE, "estimated_ready_at" TIMESTAMP WITH TIME ZONE, "subtotal_cents" integer NOT NULL, "modifier_cents" integer NOT NULL DEFAULT '0', "discount_cents" integer NOT NULL DEFAULT '0', "tax_cents" integer NOT NULL, "tip_cents" integer NOT NULL DEFAULT '0', "total_cents" integer NOT NULL, "stripe_payment_id" text, "clover_order_id" text, "notes" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_59d6b7756aeb6cbb43a093d15a1" UNIQUE ("idempotency_key"), CONSTRAINT "PK_710e2d4957aa5878dfe94e4ac2f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_59d6b7756aeb6cbb43a093d15a" ON "orders" ("idempotency_key") `);
        await queryRunner.query(`CREATE INDEX "IDX_65204503e71840721aa296f5a8" ON "orders" ("stripe_payment_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_4d1de0012e93852464525a2c02" ON "orders" ("clover_order_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_744315ba30953a7651688720c6" ON "orders" ("location_id", "order_status") `);
        await queryRunner.query(`CREATE INDEX "IDX_11fefa35e3ef25881234b8b89a" ON "orders" ("customer_id", "created_at") `);
        await queryRunner.query(`CREATE TABLE "order_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "order_id" uuid NOT NULL, "menu_item_id" uuid NOT NULL, "quantity" integer NOT NULL DEFAULT '1', "unit_price_cents" integer NOT NULL, "modifiers" jsonb NOT NULL DEFAULT '[]'::jsonb, CONSTRAINT "PK_005269d8574e6fac0493715c308" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "order_events" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "order_id" uuid NOT NULL, "from_status" text, "to_status" text NOT NULL, "reason" text, "created_by" text NOT NULL, "metadata" jsonb, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_cc1b82b0fcf1be577d9d7ecbf8b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_94dcb98fcac804e1a0a357a56d" ON "order_events" ("order_id", "created_at") `);
        // payment_status_enum already created above (used by orders.payment_status)
        await queryRunner.query(`CREATE TABLE "payments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "order_id" uuid NOT NULL, "stripe_payment_id" text NOT NULL, "amount_cents" integer NOT NULL, "payment_status" "public"."payment_status_enum" NOT NULL, "stripe_response" jsonb, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_c3ea9db737d00d3c0b65820f8f6" UNIQUE ("stripe_payment_id"), CONSTRAINT "PK_197ab7af18c93fbb0c9b28b4a59" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_c3ea9db737d00d3c0b65820f8f" ON "payments" ("stripe_payment_id") `);
        await queryRunner.query(`CREATE TABLE "refunds" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "order_id" uuid NOT NULL, "payment_id" uuid NOT NULL, "stripe_refund_id" text NOT NULL, "amount_cents" integer NOT NULL, "reason" text NOT NULL, "created_by" uuid NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_69110dcf7cbff0515a096de5e5a" UNIQUE ("stripe_refund_id"), CONSTRAINT "PK_5106efb01eeda7e49a78b869738" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_69110dcf7cbff0515a096de5e5" ON "refunds" ("stripe_refund_id") `);
        // clover_sync_status_enum already created above (used by orders.clover_sync_status)
        await queryRunner.query(`CREATE TABLE "clover_sync_log" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "order_id" uuid NOT NULL, "attempt_number" integer NOT NULL, "sync_status" "public"."clover_sync_status_enum" NOT NULL, "request_payload" jsonb, "response_payload" jsonb, "error_message" text, "attempted_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_8144aeaa7ed12eabda5ca737441" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_1998967534b110e73f518e53e7" ON "clover_sync_log" ("order_id", "attempt_number") `);
        await queryRunner.query(`CREATE TABLE "customer_ai_profiles" ("customer_id" uuid NOT NULL, "preferred_milk" text, "preferred_size" text, "preferred_temp" text, "disliked_items" text array NOT NULL DEFAULT '{}'::text[], "dietary_flags" text array NOT NULL DEFAULT '{}'::text[], "price_segment" text, "impulse_buyer" boolean, "deal_responsive" boolean, "adventurousness" numeric(3,2), "churn_score" numeric(3,2), "lifetime_value_cents" integer, "avg_order_value_cents" integer, "usual_order_time" TIME, "usual_order_days" integer array NOT NULL DEFAULT '{}'::int[], "notification_open_rate" numeric(4,3), "recommendation_accept_rate" numeric(4,3), "last_calculated_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_86fac8dd3267a8940661db1888f" PRIMARY KEY ("customer_id"))`);
        await queryRunner.query(`CREATE TYPE "public"."behavior_event_type_enum" AS ENUM('menu_viewed', 'item_viewed', 'cart_added', 'cart_removed', 'offer_seen', 'offer_redeemed', 'app_opened')`);
        await queryRunner.query(`CREATE TABLE "behavior_events" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "customer_id" uuid NOT NULL, "event_type" "public"."behavior_event_type_enum" NOT NULL, "item_id" uuid, "duration_seconds" integer, "metadata" jsonb, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_2de09b711acc961f07609390a52" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_5c85a388ba6358fdf364713cc3" ON "behavior_events" ("event_type", "created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_b214c4067ca3a23533d1543142" ON "behavior_events" ("customer_id", "created_at") `);
        await queryRunner.query(`CREATE TABLE "ai_decisions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "customer_id" uuid NOT NULL, "trigger" text NOT NULL, "decision_type" text NOT NULL, "recommendation_item_id" uuid, "offer_type" text, "offer_value_cents" integer, "confidence" numeric(4,3), "was_shown" boolean NOT NULL DEFAULT false, "was_accepted" boolean, "revenue_generated_cents" integer, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "resolved_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_4824e83ce31a5463a5b75d9737d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c85fb7038864403c67dc448178" ON "ai_decisions" ("customer_id", "created_at") `);
        await queryRunner.query(`CREATE TABLE "offers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "customer_id" uuid NOT NULL, "type" text NOT NULL, "value_cents" integer NOT NULL, "description" text, "sent_at" TIMESTAMP WITH TIME ZONE, "opened_at" TIMESTAMP WITH TIME ZONE, "redeemed_at" TIMESTAMP WITH TIME ZONE, "expires_at" TIMESTAMP WITH TIME ZONE, "revenue_attributed_cents" integer, CONSTRAINT "PK_4c88e956195bba85977da21b8f4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_40af55b3ac7d6265ae51895207" ON "offers" ("customer_id", "sent_at") `);
        await queryRunner.query(`CREATE TABLE "loyalty_accounts" ("customer_id" uuid NOT NULL, "points_balance" integer NOT NULL DEFAULT '0', "lifetime_points" integer NOT NULL DEFAULT '0', "tier" text NOT NULL DEFAULT 'BRONZE', "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_1c7eaf158aad7e4a839232cc9ba" PRIMARY KEY ("customer_id"))`);
        await queryRunner.query(`CREATE TABLE "loyalty_transactions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "customer_id" uuid NOT NULL, "order_id" uuid, "points_delta" integer NOT NULL, "reason" text NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_df453f678b7575221b335673362" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ad58ccbbbec72e5e7543a75941" ON "loyalty_transactions" ("customer_id", "created_at") `);
        await queryRunner.query(`CREATE TYPE "public"."outbox_event_type_enum" AS ENUM('ORDER_PAID', 'ORDER_CANCELLED', 'ORDER_READY', 'ORDER_PICKED_UP', 'REFUND_CREATED', 'ITEM_OUT_OF_STOCK')`);
        await queryRunner.query(`CREATE TYPE "public"."outbox_status_enum" AS ENUM('PENDING', 'PROCESSED', 'DEAD')`);
        await queryRunner.query(`CREATE TABLE "outbox_events" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "event_type" "public"."outbox_event_type_enum" NOT NULL, "payload" jsonb NOT NULL, "status" "public"."outbox_status_enum" NOT NULL DEFAULT 'PENDING', "attempts" integer NOT NULL DEFAULT '0', "last_error" text, "processed_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_6689a16c00d09b8089f6237f1d2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_cc0d2a98103923a41a9aebc384" ON "outbox_events" ("status", "created_at") `);
        await queryRunner.query(`CREATE TABLE "feature_flags" ("key" text NOT NULL, "enabled" boolean NOT NULL DEFAULT false, "rollout_pct" integer NOT NULL DEFAULT '0', "description" text, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_36d0344370584b4d6a953c53a69" PRIMARY KEY ("key"))`);
        await queryRunner.query(`ALTER TABLE "location_hours" ADD CONSTRAINT "FK_87a038955f92d9e83f3ee9c41dc" FOREIGN KEY ("location_id") REFERENCES "locations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "location_settings" ADD CONSTRAINT "FK_84d2853faad00c6eebb7cd6e8c0" FOREIGN KEY ("location_id") REFERENCES "locations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "staff_users" ADD CONSTRAINT "FK_c2fe04023d33c81ee8266eabff6" FOREIGN KEY ("location_id") REFERENCES "locations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "menu_categories" ADD CONSTRAINT "FK_35f0ccf11c04b350284b1943ac4" FOREIGN KEY ("location_id") REFERENCES "locations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "menu_items" ADD CONSTRAINT "FK_20cff56c44dd4fe52d5aa2b96f8" FOREIGN KEY ("category_id") REFERENCES "menu_categories"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "modifier_groups" ADD CONSTRAINT "FK_ee41e5f96cb9295f08c73daddef" FOREIGN KEY ("item_id") REFERENCES "menu_items"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "modifiers" ADD CONSTRAINT "FK_b87db3123428d033c74e77cc3b3" FOREIGN KEY ("group_id") REFERENCES "modifier_groups"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory" ADD CONSTRAINT "FK_94f5cbcb5f280f2f30bd4a9fd90" FOREIGN KEY ("item_id") REFERENCES "menu_items"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory" ADD CONSTRAINT "FK_1eea99c8c645d7541002473a015" FOREIGN KEY ("location_id") REFERENCES "locations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory" ADD CONSTRAINT "FK_6cb4135e32d8f344d1b0fd60303" FOREIGN KEY ("updated_by") REFERENCES "staff_users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pricing_rules" ADD CONSTRAINT "FK_2e57fd74dc2dd68dfd1cd8f84b5" FOREIGN KEY ("location_id") REFERENCES "locations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_772d0ce0473ac2ccfa26060dbe9" FOREIGN KEY ("customer_id") REFERENCES "customers"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_90e29013d1252e005e70beb4f46" FOREIGN KEY ("location_id") REFERENCES "locations"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "FK_145532db85752b29c57d2b7b1f1" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "FK_e462517174f561ece2916701c0a" FOREIGN KEY ("menu_item_id") REFERENCES "menu_items"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_events" ADD CONSTRAINT "FK_b33cbf9a59cbee112d94bcb59de" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_b2f7b823a21562eeca20e72b006" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "refunds" ADD CONSTRAINT "FK_a42db6369017df60549539f5567" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "refunds" ADD CONSTRAINT "FK_7f48aa5d56c42aeb495db016683" FOREIGN KEY ("payment_id") REFERENCES "payments"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "refunds" ADD CONSTRAINT "FK_dcf8f786aaeb2746c93a332b635" FOREIGN KEY ("created_by") REFERENCES "staff_users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "clover_sync_log" ADD CONSTRAINT "FK_9c42fdb3f30bafca758000e770f" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "customer_ai_profiles" ADD CONSTRAINT "FK_86fac8dd3267a8940661db1888f" FOREIGN KEY ("customer_id") REFERENCES "customers"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "behavior_events" ADD CONSTRAINT "FK_1e1a714778a3246993bb0cb9b03" FOREIGN KEY ("customer_id") REFERENCES "customers"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ai_decisions" ADD CONSTRAINT "FK_f2bad0189026fb43338d849a02e" FOREIGN KEY ("customer_id") REFERENCES "customers"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "offers" ADD CONSTRAINT "FK_83192d84ff9401aeb54c3f37933" FOREIGN KEY ("customer_id") REFERENCES "customers"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "loyalty_accounts" ADD CONSTRAINT "FK_1c7eaf158aad7e4a839232cc9ba" FOREIGN KEY ("customer_id") REFERENCES "customers"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "loyalty_transactions" ADD CONSTRAINT "FK_39f39219f9587d34638ccde8b67" FOREIGN KEY ("customer_id") REFERENCES "customers"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "loyalty_transactions" ADD CONSTRAINT "FK_8be4d5110bff05094d246d62aed" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "loyalty_transactions" DROP CONSTRAINT "FK_8be4d5110bff05094d246d62aed"`);
        await queryRunner.query(`ALTER TABLE "loyalty_transactions" DROP CONSTRAINT "FK_39f39219f9587d34638ccde8b67"`);
        await queryRunner.query(`ALTER TABLE "loyalty_accounts" DROP CONSTRAINT "FK_1c7eaf158aad7e4a839232cc9ba"`);
        await queryRunner.query(`ALTER TABLE "offers" DROP CONSTRAINT "FK_83192d84ff9401aeb54c3f37933"`);
        await queryRunner.query(`ALTER TABLE "ai_decisions" DROP CONSTRAINT "FK_f2bad0189026fb43338d849a02e"`);
        await queryRunner.query(`ALTER TABLE "behavior_events" DROP CONSTRAINT "FK_1e1a714778a3246993bb0cb9b03"`);
        await queryRunner.query(`ALTER TABLE "customer_ai_profiles" DROP CONSTRAINT "FK_86fac8dd3267a8940661db1888f"`);
        await queryRunner.query(`ALTER TABLE "clover_sync_log" DROP CONSTRAINT "FK_9c42fdb3f30bafca758000e770f"`);
        await queryRunner.query(`ALTER TABLE "refunds" DROP CONSTRAINT "FK_dcf8f786aaeb2746c93a332b635"`);
        await queryRunner.query(`ALTER TABLE "refunds" DROP CONSTRAINT "FK_7f48aa5d56c42aeb495db016683"`);
        await queryRunner.query(`ALTER TABLE "refunds" DROP CONSTRAINT "FK_a42db6369017df60549539f5567"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_b2f7b823a21562eeca20e72b006"`);
        await queryRunner.query(`ALTER TABLE "order_events" DROP CONSTRAINT "FK_b33cbf9a59cbee112d94bcb59de"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "FK_e462517174f561ece2916701c0a"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "FK_145532db85752b29c57d2b7b1f1"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_90e29013d1252e005e70beb4f46"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_772d0ce0473ac2ccfa26060dbe9"`);
        await queryRunner.query(`ALTER TABLE "pricing_rules" DROP CONSTRAINT "FK_2e57fd74dc2dd68dfd1cd8f84b5"`);
        await queryRunner.query(`ALTER TABLE "inventory" DROP CONSTRAINT "FK_6cb4135e32d8f344d1b0fd60303"`);
        await queryRunner.query(`ALTER TABLE "inventory" DROP CONSTRAINT "FK_1eea99c8c645d7541002473a015"`);
        await queryRunner.query(`ALTER TABLE "inventory" DROP CONSTRAINT "FK_94f5cbcb5f280f2f30bd4a9fd90"`);
        await queryRunner.query(`ALTER TABLE "modifiers" DROP CONSTRAINT "FK_b87db3123428d033c74e77cc3b3"`);
        await queryRunner.query(`ALTER TABLE "modifier_groups" DROP CONSTRAINT "FK_ee41e5f96cb9295f08c73daddef"`);
        await queryRunner.query(`ALTER TABLE "menu_items" DROP CONSTRAINT "FK_20cff56c44dd4fe52d5aa2b96f8"`);
        await queryRunner.query(`ALTER TABLE "menu_categories" DROP CONSTRAINT "FK_35f0ccf11c04b350284b1943ac4"`);
        await queryRunner.query(`ALTER TABLE "staff_users" DROP CONSTRAINT "FK_c2fe04023d33c81ee8266eabff6"`);
        await queryRunner.query(`ALTER TABLE "location_settings" DROP CONSTRAINT "FK_84d2853faad00c6eebb7cd6e8c0"`);
        await queryRunner.query(`ALTER TABLE "location_hours" DROP CONSTRAINT "FK_87a038955f92d9e83f3ee9c41dc"`);
        await queryRunner.query(`DROP TABLE "feature_flags"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cc0d2a98103923a41a9aebc384"`);
        await queryRunner.query(`DROP TABLE "outbox_events"`);
        await queryRunner.query(`DROP TYPE "public"."outbox_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."outbox_event_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ad58ccbbbec72e5e7543a75941"`);
        await queryRunner.query(`DROP TABLE "loyalty_transactions"`);
        await queryRunner.query(`DROP TABLE "loyalty_accounts"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_40af55b3ac7d6265ae51895207"`);
        await queryRunner.query(`DROP TABLE "offers"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c85fb7038864403c67dc448178"`);
        await queryRunner.query(`DROP TABLE "ai_decisions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b214c4067ca3a23533d1543142"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5c85a388ba6358fdf364713cc3"`);
        await queryRunner.query(`DROP TABLE "behavior_events"`);
        await queryRunner.query(`DROP TYPE "public"."behavior_event_type_enum"`);
        await queryRunner.query(`DROP TABLE "customer_ai_profiles"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1998967534b110e73f518e53e7"`);
        await queryRunner.query(`DROP TABLE "clover_sync_log"`);
        // clover_sync_status_enum still used by orders — dropped at the end
        await queryRunner.query(`DROP INDEX "public"."IDX_69110dcf7cbff0515a096de5e5"`);
        await queryRunner.query(`DROP TABLE "refunds"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c3ea9db737d00d3c0b65820f8f"`);
        await queryRunner.query(`DROP TABLE "payments"`);
        // payment_status_enum still used by orders — dropped at the end
        await queryRunner.query(`DROP INDEX "public"."IDX_94dcb98fcac804e1a0a357a56d"`);
        await queryRunner.query(`DROP TABLE "order_events"`);
        await queryRunner.query(`DROP TABLE "order_items"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_11fefa35e3ef25881234b8b89a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_744315ba30953a7651688720c6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4d1de0012e93852464525a2c02"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_65204503e71840721aa296f5a8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_59d6b7756aeb6cbb43a093d15a"`);
        await queryRunner.query(`DROP TABLE "orders"`);
        await queryRunner.query(`DROP TYPE "public"."pickup_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."clover_sync_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."payment_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."order_status_enum"`);
        await queryRunner.query(`DROP TABLE "pricing_rules"`);
        await queryRunner.query(`DROP TABLE "inventory"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_68f9a6a26b1cb62380a64b0be3"`);
        await queryRunner.query(`DROP TABLE "modifiers"`);
        await queryRunner.query(`DROP TABLE "modifier_groups"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c9f448f6e4d50fc4e1d4a783ca"`);
        await queryRunner.query(`DROP TABLE "menu_items"`);
        await queryRunner.query(`DROP TABLE "menu_categories"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5cdfddaf549b53bbc3d723dc2c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4f32dd66546226ea64f5573b77"`);
        await queryRunner.query(`DROP TABLE "staff_users"`);
        await queryRunner.query(`DROP TYPE "public"."staff_role_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_239f870c0c4c1d6b68eb016dfb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8536b8b85c06969f84f0c098b0"`);
        await queryRunner.query(`DROP TABLE "customers"`);
        await queryRunner.query(`DROP TABLE "location_settings"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_39d361bcd1c543a8c00011fe0c"`);
        await queryRunner.query(`DROP TABLE "location_hours"`);
        await queryRunner.query(`DROP TABLE "locations"`);
    }

}
